title: CLIJ2 (experimental alpha release)
logo: /images/clij2_logo.png
description: CLIJ2 (experimental alpha release)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
